# Generated by Django 5.2.5 on 2025-08-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
            options={
                "ordering": ["-created_datetime"],
            },
        ),
    ]
