# Generated by Django 5.2.5 on 2025-08-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
